name: Asymmetric Curve CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gcc:latest

    steps:
      - name: Install dependencies
        run: |
          apt update
          apt install -y build-essential libgmp-dev libmpfr-dev libssl-dev libgtest-dev cmake

      - name: Checkout RELIC
        uses: actions/checkout@v4
        with:
          repository: relic-toolkit/relic
          path: relic

      - name: Install RELIC asymmetric curve
        run: |
          mkdir relic/build
          cd relic/build
          ../preset/gmp-pbc-bls381.sh ..
          make
          make install

      - name: Checkout main repository
        uses: actions/checkout@v4

      - name: Install project
        run: |
          mkdir build
          cd build
          cmake ..
          make
          make install

  test:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: gcc:latest

    steps:
      - name: Run tests
        run: |
          cd build
          ctest
